spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com}
      chat:
        completions-path: ${CHAT_COMPLETIONS_PATH:/v1/chat/completions}
        options:
          model: ${OPENAI_CHAT_MODEL:gpt-4o-mini}
      embedding:
        embeddings-path: ${EMBEDDINGS_PATH:/v1/embeddings}
        options:
          model: ${EMBEDDING_MODEL:text-embedding-3-small}
          dimensions: ${EMBEDDING_DIMENSIONS:768}
          encoding-format: float
    upstage:
      api-key: ${UPSTAGE_API_KEY:}
      base-url: https://api.upstage.ai
      chat:
        options:
          model: ${UPSTAGE_CHAT_MODEL:solar-pro2}
    naver:
      api-key: ${NAVER_CLOVA_API_KEY:}
      base-url: https://clovastudio.stream.ntruss.com/v1/openai
      chat:
        completions-path: /chat/completions
        options:
          model: ${NAVER_CLOVA_CHAT_MODEL:HCX-007}
      embedding:
        embeddings-path: /embeddings
        options:
          model: ${NAVER_CLOVA_EMBEDDING_MODEL:bge-m3}
          dimensions: ${EMBEDDING_DIMENSIONS:1024}
          encoding-format: float
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: never
    vectorstore:
      pgvector:
        table-name: place_embedding
        dimensions: ${EMBEDDING_DIMENSIONS:1024}
