services:
    app:
        image: dvkbv060.kr.private-ncr.ntruss.com/airoad-backend:latest
        container_name: airoad-backend
        restart: on-failure:3
        ports:
            - "8080:8080"
        environment:
            - SPRING_PROFILES_ACTIVE=prod
        env_file:
            - .env
        networks:
            - airoad-network

networks:
    airoad-network:
        external: true