services:
    app:
        image: ghcr.io/swyp-web-11-team-4/airoad-backend:${IMAGE_TAG:-latest}
        container_name: airoad-backend
        restart: on-failure:3
        ports:
            - "8080:8080"
        environment:
            - SPRING_PROFILES_ACTIVE=prod
        env_file:
            - .env
        networks:
            - airoad-network

networks:
    airoad-network:
        external: true